#PROFILE
spring:
  profiles:
    active: zone1

eureka:
  environment: ecommerce-test
  instance:
    hostname: localhost
  client:
    region: region-1
    service-url:
      zone1: http://localhost:8761/eureka/,http://127.0.0.1:8762/eureka/
      zone2: http://127.0.0.1:8762/eureka/,http://localhost:8761/eureka/